[functions.account-manager]
enabled = true
verify_jwt = true
import_map = "./functions/account-manager/deno.json"
entrypoint = "./functions/account-manager/index.ts"

[functions.annotation-service]
verify_jwt = false

[functions.orthanc-proxy]
verify_jwt = false
